
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"mw-RiderPages-newer","number":42,"title":"Mw - rider application \"show\" page","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/42"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-field-names-hover","number":41,"title":"Andy field names hover (optional part from issue #94)","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/41"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ride-request-field-names","number":40,"title":"Andy ride request field names","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/40"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"KV-DriverAvailibilityTable","number":34,"title":"KV - DriverAvailibilityTable, DriverAvailibilityUtils","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/34"}]
