
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-driver-availability-page-stories","number":49,"title":"AW - DriverAvailability Pages + Stories","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/49"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"KV-DriverPages","number":48,"title":"KV - Driver Availability: Driver Pages","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-2/pull/48"}]
